version: "3.9"
services:
  postgres:
    image: "postgres:14.3"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    ports:
      - ${DATABASE_PORT}:5432
