name: Deploy

on:
  push:
    branches:
      - develop
      - feat/deploy

jobs:
  dev-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --file Dockerfile.prod --tag strapi-service:$(date +%s)
      - name: Copy repository to server with rsync
        run: rsync -avz --chown=github:www-data --chmod=Dg=rwx,Fg=rwx ./ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/home/www/my_project/
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}
