name: Strapi-service

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build strapi
        run: docker build . --file Dockerfile.prod --tag strapi-service:$(date +%s)
